package com.my.kizzy.rpc

object Constants {
    const val NAME = "name"
    const val DETAILS = "details"
    const val STATE = "state"
    const val TYPE = "type"
    const val APPLICATION = "application_id"
    const val APPLICATION_ID = "962990036020756480"
    const val START_TIMESTAMPS = "start"
    const val STOP_TIMESTAMPS = "end"
    const val TIMESTAMPS = "timestamps"
    const val LARGE_IMAGE = "large_image"
    const val SMALL_IMAGE = "small_image"
    const val ASSETS = "assets"
    const val BUTTONS = "buttons"
    const val ACTIVITIES = "activities"
    const val AFK = "afk"
    const val SINCE = "since"
    const val STATUS = "status"
    const val METADATA = "metadata"
    const val BUTTON_LINK = "button_urls"
    const val ONLINE = "online"
    const val IDLE = "idle"
    const val DND = "dnd"
    const val errorAsset = "mp:attachments/948828217312178227/948840504542498826/Kizzy.png"
}